### ISSUE TITLE
Can't Join The The New Server Build 1.2.2-11

### ISSUE THREAD

**Issue by MrMcMuffins26** [Hennamann/Wasteland#9] opened 2018-03-24 21:16 UTC
The server now loads but clients can't connect, command console spews out errors concerning the biomes for the wasteland world type. (Leveltype-Wasteland). if I generate a world in singleplayer and port it over, no one can join still and the same errors are spewed out in the command console.

entBus.post(EventBus.java:179)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraft.server.MinecraftServer.func_712
47_a(MinecraftServer.java:309)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraft.server.dedicated.DedicatedServe
r.func_71197_b(DedicatedServer.java:270)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraft.server.MinecraftServer.run(Mine
craftServer.java:484)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at java.lang.Thread.run(Unknown Source)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]: java.io.IOException: The system cannot find the pa
th specified
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at java.io.WinNTFileSystem.createFileExclusively
(Native Method)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at java.io.File.createNewFile(Unknown Source)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at com.legacy.wasteland.world.util.WastelandWorl
dData.createFile(WastelandWorldData.java:41)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at com.legacy.wasteland.WastelandEventHandler.lo
adData(WastelandEventHandler.java:36)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraftforge.fml.common.eventhandler.AS
MEventHandler_12_WastelandEventHandler_loadData_Load.invoke(.dynamic)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraftforge.fml.common.eventhandler.AS
MEventHandler.invoke(ASMEventHandler.java:90)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraftforge.fml.common.eventhandler.Ev
entBus.post(EventBus.java:179)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraft.server.MinecraftServer.func_712
47_a(MinecraftServer.java:309)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraft.server.dedicated.DedicatedServe
r.func_71197_b(DedicatedServer.java:270)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at net.minecraft.server.MinecraftServer.run(Mine
craftServer.java:484)
[21:14:55] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:createFile:45]:   at java.lang.Thread.run(Unknown Source)
[21:14:55] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g start region for level 0
[21:14:56] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g spawn area: 14%
[21:14:57] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g spawn area: 28%
[21:14:58] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g spawn area: 45%
[21:14:59] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g spawn area: 59%
[21:15:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g spawn area: 73%
[21:15:01] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g spawn area: 86%
[21:15:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparin
g spawn area: 99%
[21:15:02] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]
: Done (14.439s)! For help, type "help" or "?"
[21:15:02] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]
: Starting GS4 status listener
[21:15:02] [Query Listener #1/INFO] [net.minecraft.server.MinecraftServer]: Quer
y running on 192.168.0.15:25565
[21:15:29] [User Authenticator #1/INFO] [net.minecraft.server.network.NetHandler
LoginServer]: UUID of player MrMcMuffins is a87a3101-9a8f-4307-923b-935ec82b4559

[21:15:30] [Netty Server IO #2/INFO] [FML]: Client protocol version 2
[21:15:30] [Netty Server IO #2/INFO] [FML]: Client attempting to join with 5 mod
s : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.2.2629,wastelands@1.2.2,mcp@9.42
[21:15:30] [Server thread/INFO] [FML]: [Server thread] Server side modded connec
tion established
[21:15:30] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Mr
McMuffins[/81.106.150.225:56450] logged in with entity id 475 at (342.5, 93.0, -
357.5)
[21:15:30] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]
: MrMcMuffins joined the game
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]: java.io.FileNotFoundException: saves\DexSink\d
ata\wasteland_cache.dat (The system cannot find the path specified)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at java.io.FileInputStream.open0(Native
Method)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at java.io.FileInputStream.open(Unknown
Source)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at java.io.FileInputStream.<init>(Unknow
n Source)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at com.legacy.wasteland.world.util.Waste
landWorldData.getPlayerNames(WastelandWorldData.java:54)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at com.legacy.wasteland.WastelandEventHa
ndler.isNewPlayer(WastelandEventHandler.java:120)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at com.legacy.wasteland.WastelandEventHa
ndler.setSpawnpointEvent(WastelandEventHandler.java:64)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraftforge.fml.common.eventha
ndler.ASMEventHandler_11_WastelandEventHandler_setSpawnpointEvent_EntityJoinWorl
dEvent.invoke(.dynamic)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraftforge.fml.common.eventha
ndler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraftforge.fml.common.eventha
ndler.EventBus.post(EventBus.java:179)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.world.World.func_72838_
d(World.java:1205)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.world.WorldServer.func_
72838_d(WorldServer.java:1058)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.server.management.Playe
rList.func_72377_c(PlayerList.java:376)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.server.management.Playe
rList.initializeConnectionToPlayer(PlayerList.java:165)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java
:256)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.network.NetworkManager.
func_74428_b(NetworkManager.java:285)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.network.NetworkSystem.f
unc_151269_c(NetworkSystem.java:180)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.server.MinecraftServer.
func_71190_q(MinecraftServer.java:788)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.server.dedicated.Dedica
tedServer.func_71190_q(DedicatedServer.java:396)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.server.MinecraftServer.
func_71217_p(MinecraftServer.java:666)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:524)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:getPlayerNames:58]:       at java.lang.Thread.run(Unknown Source)
[21:15:30] [Server thread/INFO] [STDOUT]: [com.legacy.wasteland.world.biome.deco
rations.BiomeDecoratorWasteland:spawnBunker:248]: BlockPos{x=340, y=84, z=-360}
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]: java.io.FileNotFoundException: saves\DexSink\dat
a\wasteland_cache.dat (The system cannot find the path specified)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at java.io.FileInputStream.open0(Native
Method)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at java.io.FileInputStream.open(Unknown
Source)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at java.io.FileInputStream.<init>(Unknow
n Source)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at com.legacy.wasteland.world.util.Waste
landWorldData.saveSpawnLoc(WastelandWorldData.java:90)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at com.legacy.wasteland.WastelandEventHa
ndler.setSpawnpointEvent(WastelandEventHandler.java:75)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraftforge.fml.common.eventha
ndler.ASMEventHandler_11_WastelandEventHandler_setSpawnpointEvent_EntityJoinWorl
dEvent.invoke(.dynamic)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraftforge.fml.common.eventha
ndler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraftforge.fml.common.eventha
ndler.EventBus.post(EventBus.java:179)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.world.World.func_72838_
d(World.java:1205)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.world.WorldServer.func_
72838_d(WorldServer.java:1058)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.server.management.Playe
rList.func_72377_c(PlayerList.java:376)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.server.management.Playe
rList.initializeConnectionToPlayer(PlayerList.java:165)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java
:256)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.network.NetworkManager.
func_74428_b(NetworkManager.java:285)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.network.NetworkSystem.f
unc_151269_c(NetworkSystem.java:180)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.server.MinecraftServer.
func_71190_q(MinecraftServer.java:788)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.server.dedicated.Dedica
tedServer.func_71190_q(DedicatedServer.java:396)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.server.MinecraftServer.
func_71217_p(MinecraftServer.java:666)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:524)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:saveSpawnLoc:99]:         at java.lang.Thread.run(Unknown Source)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]: java.io.FileNotFoundException: saves\DexSink\
data\wasteland_cache.dat (The system cannot find the path specified)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at java.io.FileInputStream.open0(Native
Method)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at java.io.FileInputStream.open(Unknown
Source)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at java.io.FileInputStream.<init>(Unknow
n Source)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at com.legacy.wasteland.world.util.Waste
landWorldData.savePlayerNames(WastelandWorldData.java:66)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at com.legacy.wasteland.world.util.Waste
landWorldData.savePlayerName(WastelandWorldData.java:85)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at com.legacy.wasteland.WastelandEventHa
ndler.setSpawnpointEvent(WastelandEventHandler.java:84)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraftforge.fml.common.eventha
ndler.ASMEventHandler_11_WastelandEventHandler_setSpawnpointEvent_EntityJoinWorl
dEvent.invoke(.dynamic)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraftforge.fml.common.eventha
ndler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraftforge.fml.common.eventha
ndler.EventBus.post(EventBus.java:179)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.world.World.func_72838_
d(World.java:1205)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.world.WorldServer.func_
72838_d(WorldServer.java:1058)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.server.management.Playe
rList.func_72377_c(PlayerList.java:376)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.server.management.Playe
rList.initializeConnectionToPlayer(PlayerList.java:165)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java
:256)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraftforge.fml.common.network
.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.network.NetworkManager.
func_74428_b(NetworkManager.java:285)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.network.NetworkSystem.f
unc_151269_c(NetworkSystem.java:180)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.server.MinecraftServer.
func_71190_q(MinecraftServer.java:788)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.server.dedicated.Dedica
tedServer.func_71190_q(DedicatedServer.java:396)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.server.MinecraftServer.
func_71217_p(MinecraftServer.java:666)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:524)
[21:15:30] [Server thread/INFO] [STDERR]: [com.legacy.wasteland.world.util.Waste
landWorldData:savePlayerNames:77]:      at java.lang.Thread.run(Unknown Source)
>

**Comment by C0LiSii0N** [comment] 2018-04-15 09:17
Got the same, find out that it's because the mod try to find a file(wasteland_cache.dat) in a save directory when it should look in the world directory(probably due to the fact that in single player the path is different). I created the saves directory and copied my world into it then the error stopped but still can't connect(no error in the console :/) also by default the server don't create the "wasteland_cache.dat" in the world directory I had to create a solo world then move the files in my server folder.

I just find out that I got connected properly but my client can't show the server(block on logging in page) because i got killed by a zombie and i can kick myself..

**Comment by darkphan** [comment] 2018-06-10 23:04
Same here, was really looking forward to using this mod in an upcoming modpack :/

**Comment by Axebeard2025** [comment] 2018-07-17 13:38
One problem I see right away is that when wastelands is run as a server, it is looking for the "wasteland_cache.dat" file in "saves\world\data\".  For a server, this should be "\world\data\wasteland_cache.dat"

Just for giggles, I copied a wasteland_cache.dat file from a single player to the correct location in the server.  RESULT:  no change.

Then I created a "\saves\world\data\wasteland_cache.dat" on my server, and got the following error:

`[08:41:17] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
	at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:376) [pl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:165) [pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]`

Hope this helps

**Comment by Hennamann** [comment] 2019-02-17 21:02
I'll look into this soon!

**Comment by Hennamann** [comment] 2021-06-13 11:26
I'm assuming that this is fixed by the latest update. Comment on this issue if the problem persists and i´ll reopen it.

**Closed as completed by Hennamann** 2021-06-13 11:26 UTC
Labels: bug

**Comment by gangeous** [comment] 2021-12-01 17:53
I have the same issue, so it seems like it hasn't been fixed :/
