### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by MrMcMuffins26** [Hennamann/Wasteland#8] opened 2018-03-24 14:41 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 24/03/18 00:41
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wasteland Mod (wastelands)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderLivingBase
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:127)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:111)
	at com.legacy.wasteland.Wasteland.registerEvent(Wasteland.java:46)
	at com.legacy.wasteland.Wasteland.init(Wasteland.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.RenderLivingBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@718607eb from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more
Caused by: java.lang.RuntimeException: Attempted to load class caa for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 967969808 bytes (923 MB) / 2402287616 bytes (2291 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx5G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2632 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                  | Signature                                |
	|:----- |:-------------------- |:------------------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft            | 1.12.2                   | minecraft.jar                           | None                                     |
	| UCHI  | mcp                  | 9.42                     | minecraft.jar                           | None                                     |
	| UCHI  | FML                  | 8.0.99.99                | forge-1.12.2-14.23.2.2632-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                | 14.23.2.2632             | forge-1.12.2-14.23.2.2632-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                           | None                                     |
	| UCHI  | chisel               | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar            | None                                     |
	| UCHI  | extendedrenderer     | v1.0                     | coroutil-1.12.1-1.1.24.jar              | None                                     |
	| UCHI  | coroutil             | 1.12.1-1.1.24            | coroutil-1.12.1-1.1.24.jar              | None                                     |
	| UCHI  | configmod            | v1.0                     | coroutil-1.12.1-1.1.24.jar              | None                                     |
	| UCHI  | crafttweaker         | 4.1.6                    | CraftTweaker2-1.12-4.1.6.jar            | None                                     |
	| UCHI  | jei                  | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                | None                                     |
	| UCHI  | crafttweakerjei      | 2.0.0                    | CraftTweaker2-1.12-4.1.6.jar            | None                                     |
	| UCHI  | immersiveengineering | 0.12-80                  | ImmersiveEngineering-0.12-80.jar        | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHI  | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHI  | lostcities           | 2.0.6                    | lostcities-1.12-2.0.6.jar               | None                                     |
	| UCHI  | mcjtylib_ng          | 2.6.6                    | mcjtylib-1.12-2.6.6.jar                 | None                                     |
	| UCHI  | mercurius_updater    | 1.0                      | MercuriusUpdater-1.12.2.jar             | None                                     |
	| UCHI  | nuclearcraft         | 2.9e                     | NuclearCraft-2.9e--1.12.2.jar           | None                                     |
	| UCHI  | reccomplex           | 1.4.7                    | RecurrentComplex-1.4.7.jar              | None                                     |
	| UCHE  | wastelands           | 1.2.2                    | Wastelands-1.12-1.2.2-9-universal.jar   | None                                     |
	| UCHI  | weather2             | 1.12.1-2.5.8             | weather2-1.12.1-2.5.8.jar               | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Whenever I remove the wasteland reborn jar the server starts as normal though. Would appreciate any help on the matter.

**Comment by Hennamann** [comment] 2018-03-24 16:00
This is a duplicate of issue #5 i have yet to push the fix to Curse, so use this build instead which contains a fix: https://maven.henrikstabell.com/com/legacy/wastelands/Wastelands-1.12/1.2.2-11/Wastelands-1.12-1.2.2-11-universal.jar

**Closed as completed by Hennamann** 2018-03-24 16:00 UTC
Labels: bug, duplicate
